#端口配置
server:
  port: 8888
#jdbc配置
spring:
  datasource:
    username: a913a1538f76c6ac
    password: b5a5877256f1eec1
    url: jdbc:mysql://114.115.142.124:3306/manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.work.model
  configuration:
    map-underscore-to-camel-case: true
#mybatis:
#  #  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#mapper:
#  mappers: com.work.mapper.BaseMapper
#  not-empty: false
#  identity: mysql